import { Metadata } from 'next'
import { ReactNode } from 'react'
import './globals.css'
import { Poppins } from 'next/font/google'
import { Body, Html, Component } from '@meonode/ui'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default Component(({ children }: { children: ReactNode }) => {
  return Html({
    lang: 'en',
    children: [
      Body({
        className: `${poppins.variable} antialiased min-h-dvh flex flex-col`,
        children,
      }),
    ],
  })
})
